import crypto from "crypto";

/**
 * Prefix carried by every API key generated by current releases.
 *
 * Keys issued before this prefix existed are bare UUIDs and remain valid.
 * Nothing in the authentication path may assume the prefix is present: key
 * lookups are an exact match on the stored value, and adding a shape check
 * would invalidate every legacy key in a live database.
 */
export const API_KEY_PREFIX = "fsk_live_";

/**
 * Bytes of randomness in the generated portion, from crypto.randomBytes.
 * 16 bytes is 128 bits, rendered as 32 hexadecimal characters.
 */
const API_KEY_RANDOM_BYTES = 16;

/**
 * Generates a new API key, for example:
 *   fsk_live_9f2a7c41b8e35d06a1c9f4e72b8d5a30
 *
 * The prefix makes a leaked key identifiable in logs and greppable by secret
 * scanners; the hexadecimal body keeps the value safe to paste into headers,
 * URLs and shell commands without escaping.
 */
export function generateApiKey(): string {
  const random = crypto.randomBytes(API_KEY_RANDOM_BYTES).toString("hex");
  return `${API_KEY_PREFIX}${random}`;
}
